const errorHandler = require('./errorHnadler');
const {
	BAD_REQUEST,
	ALREADY_EXISTS,
	FIELD_MISSING,
	NOT_FOUND,
	INTERNAL_SERVER_ERROR,
	UNKNOWN_ERROR,
	FAILED_TO_LOGIN,
	MONGO_CONNECTION_ERROR,
} = require('./errorMessage');

module.exports = {
	errorHandler,
	BAD_REQUEST,
	ALREADY_EXISTS,
	FIELD_MISSING,
	NOT_FOUND,
	INTERNAL_SERVER_ERROR,
	UNKNOWN_ERROR,
	FAILED_TO_LOGIN,
	MONGO_CONNECTION_ERROR,
};
